os: osx
addons:
  chrome: stable
language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: nd0ut.me@gmail.com
  api_key:
    secure: A7EFBEHn8uQmconCTdWggOd4loxCIfA0Zrd1LLmmCgERMFxQJUTvKXDcEJbDzeIrEzdcErI6O17awLYlt8I+d/6XXxzFhUZIk9idYodRWCbLxNFb7m8j9T7lkl8ykTTO4cS3O1YCVG12Jg1B0bly4bqDPV+/KD3mq0sUYoFn0v73o9LdPP6ETQYVeWufLEdNv/dynSLO+l8LTNYazCv2TM/pB+rRT6XCajeYYXefZZmnLfRUyFLc7ttL6moSFZKpUG1hUEZ8mIkPfbHeb0pVUrFP1ODcAlzxf+dGV6N8OO9haWrqlYMEkctXzmSlbaCQEXTQEXCFUXbW2wB1N4tH1VSIzF81vwSlZJHo0lnMn5/fGGn9JQbNyKCT59dc+guG2UGLb05keH6d1mF9smnjhTLqej71/d0/DB9E+72qdEc3ozeyXFrcea8hiWQoT+g6Jrqqcyhdvun4npY9vXibpazENpV1Y5LcMulndhav76FnJ+aF6PKRBlTdtaHeyu6zGLe/Esp0+koOijLUUvAMZeY/olokJHd0IKNmZvsVEPYYWbz6JMRruCAkqwU/WIpPJnxrjndr49sWURcj30oxVjH/xm4Bx6cQEc1B8UdQ3P6JTbF8qBK5sVzSXp1HExXvRhOwx7Kvchri++ae2Kl0K55SIPpXO1+HGwHYYGGXf7o=
  skip_cleanup: true
  on:
    tags: true
